apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ create your deployment name as 'db-example-yourNameNoSpace' }}
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      component: db-examples
      uploader: {{ insert your name withour spaces }}
  template:
    metadata:
      labels:
        component: db-examples
        uploader: {{ insert your name withour spaces }}
    spec:
      containers:
        - name: wp-database-examples
          image: {{ insert image name from your Docker hub }}
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          resources:
            limits:
              cpu: 20m
              memory: 32Mi
              ephemeral-storage: 16Mi
            requests:
              cpu: 20m
              memory: 32Mi
          env:
            - name: ENSAAS_SERVICES
              valueFrom:
                secretKeyRef:
                  name: {{ insert your secret }}
                  key: ENSAAS_SERVICES