apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ create your ingress name as 'db-example-yourNameNoSpace' }}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    # host name should have the format ingressMetadataName.namespace.cluster.en.internal
    - host: {{ create your host name }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ insert the name under metadata in service.yaml }}
              servicePort: 3000