apiVersion: v1
kind: Service
metadata:
  name: {{ create your service name as 'db-example-yourNameNoSpace' }}
spec:
  type: ClusterIP
  selector:
    component: db-examples
    uploader: {{ insert your name withour spaces }}
  ports:
    - port: 3000
      targetPort: 5000